# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AsAtPredicateContract(Model):
    """AsAtPredicateContract.

    :param value:
    :type value: str
    :param date_time_offset:
    :type date_time_offset: datetime
    """

    _attribute_map = {
        'value': {'key': 'value', 'type': 'str'},
        'date_time_offset': {'key': 'dateTimeOffset', 'type': 'iso-8601'},
    }

    def __init__(self, value=None, date_time_offset=None):
        super(AsAtPredicateContract, self).__init__()
        self.value = value
        self.date_time_offset = date_time_offset
