# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AttributeExpression(Model):
    """AttributeExpression.

    :param attribute_name:
    :type attribute_name: str
    :param operator: Possible values include: 'Undefined', 'Equals',
     'NotEquals', 'GreaterThan', 'GreaterThanOrEqualTo', 'LessThan',
     'LessThanOrEqualTo', 'In'
    :type operator: str or ~shrine.models.enum
    :param text_value:
    :type text_value: str
    :param numeric_value:
    :type numeric_value: float
    """

    _validation = {
        'attribute_name': {'required': True, 'min_length': 1},
        'operator': {'required': True},
    }

    _attribute_map = {
        'attribute_name': {'key': 'attributeName', 'type': 'str'},
        'operator': {'key': 'operator', 'type': 'str'},
        'text_value': {'key': 'textValue', 'type': 'str'},
        'numeric_value': {'key': 'numericValue', 'type': 'float'},
    }

    def __init__(self, attribute_name, operator, text_value=None, numeric_value=None):
        super(AttributeExpression, self).__init__()
        self.attribute_name = attribute_name
        self.operator = operator
        self.text_value = text_value
        self.numeric_value = numeric_value
