# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EffectiveDateHasQuality(Model):
    """EffectiveDateHasQuality.

    :param quality: Possible values include: 'Undefined',
     'IsFirstDayOfAnyMonth', 'IsLastDayOfAnyMonth', 'IsBusinessDayOfAnyMonth',
     'IsFirstDayOfTheCurrentMonth', 'IsLastDayOfTheCurrentMonth',
     'IsBusinessDayOfTheCurrentMonth', 'IsBeforeMidday', 'IsBefore5pm',
     'IsAfter5pm'
    :type quality: str or ~shrine.models.enum
    """

    _attribute_map = {
        'quality': {'key': 'quality', 'type': 'str'},
    }

    def __init__(self, quality=None):
        super(EffectiveDateHasQuality, self).__init__()
        self.quality = quality
