# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ForSpec(Model):
    """ForSpec.

    :param as_at_range_for_spec:
    :type as_at_range_for_spec: ~shrine.models.AsAtRangeForSpec
    :param as_at_relative:
    :type as_at_relative: ~shrine.models.AsAtRelative
    :param effective_date_has_quality:
    :type effective_date_has_quality: ~shrine.models.EffectiveDateHasQuality
    :param effective_date_relative:
    :type effective_date_relative: ~shrine.models.EffectiveDateRelative
    :param effective_range:
    :type effective_range: ~shrine.models.EffectiveRange
    """

    _attribute_map = {
        'as_at_range_for_spec': {'key': 'asAtRangeForSpec', 'type': 'AsAtRangeForSpec'},
        'as_at_relative': {'key': 'asAtRelative', 'type': 'AsAtRelative'},
        'effective_date_has_quality': {'key': 'effectiveDateHasQuality', 'type': 'EffectiveDateHasQuality'},
        'effective_date_relative': {'key': 'effectiveDateRelative', 'type': 'EffectiveDateRelative'},
        'effective_range': {'key': 'effectiveRange', 'type': 'EffectiveRange'},
    }

    def __init__(self, as_at_range_for_spec=None, as_at_relative=None, effective_date_has_quality=None, effective_date_relative=None, effective_range=None):
        super(ForSpec, self).__init__()
        self.as_at_range_for_spec = as_at_range_for_spec
        self.as_at_relative = as_at_relative
        self.effective_date_has_quality = effective_date_has_quality
        self.effective_date_relative = effective_date_relative
        self.effective_range = effective_range
