# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HowSpec(Model):
    """HowSpec.

    :param type:
    :type type: str
    :param parameters:
    :type parameters: list[~shrine.models.KeyValuePairStringString]
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': '[KeyValuePairStringString]'},
    }

    def __init__(self, type=None, parameters=None):
        super(HowSpec, self).__init__()
        self.type = type
        self.parameters = parameters
