# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IfExpression(Model):
    """IfExpression.

    :param if_request_header_expression:
    :type if_request_header_expression:
     ~shrine.models.IfRequestHeaderExpression
    :param if_identity_claim_expression:
    :type if_identity_claim_expression:
     ~shrine.models.IfIdentityClaimExpression
    :param if_identity_scope_expression:
    :type if_identity_scope_expression:
     ~shrine.models.IfIdentityScopeExpression
    """

    _attribute_map = {
        'if_request_header_expression': {'key': 'ifRequestHeaderExpression', 'type': 'IfRequestHeaderExpression'},
        'if_identity_claim_expression': {'key': 'ifIdentityClaimExpression', 'type': 'IfIdentityClaimExpression'},
        'if_identity_scope_expression': {'key': 'ifIdentityScopeExpression', 'type': 'IfIdentityScopeExpression'},
    }

    def __init__(self, if_request_header_expression=None, if_identity_claim_expression=None, if_identity_scope_expression=None):
        super(IfExpression, self).__init__()
        self.if_request_header_expression = if_request_header_expression
        self.if_identity_claim_expression = if_identity_claim_expression
        self.if_identity_scope_expression = if_identity_scope_expression
