# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PathDefinition(Model):
    """PathDefinition.

    :param attribute_path_definition:
    :type attribute_path_definition: ~shrine.models.AttributePathDefinition
    :param id_path_definition:
    :type id_path_definition: ~shrine.models.IdPathDefinition
    :param match_all_path_definition:
    :type match_all_path_definition: ~shrine.models.MatchAllPathDefinition
    :param policy_path_definition:
    :type policy_path_definition: ~shrine.models.PolicyPathDefinition
    """

    _attribute_map = {
        'attribute_path_definition': {'key': 'attributePathDefinition', 'type': 'AttributePathDefinition'},
        'id_path_definition': {'key': 'idPathDefinition', 'type': 'IdPathDefinition'},
        'match_all_path_definition': {'key': 'matchAllPathDefinition', 'type': 'MatchAllPathDefinition'},
        'policy_path_definition': {'key': 'policyPathDefinition', 'type': 'PolicyPathDefinition'},
    }

    def __init__(self, attribute_path_definition=None, id_path_definition=None, match_all_path_definition=None, policy_path_definition=None):
        super(PathDefinition, self).__init__()
        self.attribute_path_definition = attribute_path_definition
        self.id_path_definition = id_path_definition
        self.match_all_path_definition = match_all_path_definition
        self.policy_path_definition = policy_path_definition
