# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PolicyCollectionId(Model):
    """PolicyCollectionId.

    :param scope:
    :type scope: str
    :param code:
    :type code: str
    """

    _validation = {
        'scope': {'max_length': 100, 'min_length': 3},
        'code': {'required': True, 'max_length': 50, 'min_length': 3},
    }

    _attribute_map = {
        'scope': {'key': 'scope', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
    }

    def __init__(self, code, scope=None):
        super(PolicyCollectionId, self).__init__()
        self.scope = scope
        self.code = code
