# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RequestDetails(Model):
    """The details of the requested evaluation.

    :param action: The action that is requested to be performed on the
     specified resource
    :type action: ~shrine.models.RequestedActionKey
    :param from_effective_date: The start date for the requested effective
     date range for the resource (if null, UtcNow)
    :type from_effective_date: datetime
    :param to_effective_date: The end date for the requested effective date
     range for the resource (if null, same as from date)
    :type to_effective_date: datetime
    :param from_as_at: The requested AsAt date for the resource (if null,
     Latest). If specifying a range of AsAt dates, this is the lower bounds.
    :type from_as_at: datetime
    :param to_as_at: Upper bound if specifying a request that requires a range
     of AsAt dates. This is used if specifying the desire to grant access for a
     user between an AsAt range.
    :type to_as_at: datetime
    """

    _validation = {
        'action': {'required': True},
    }

    _attribute_map = {
        'action': {'key': 'action', 'type': 'RequestedActionKey'},
        'from_effective_date': {'key': 'fromEffectiveDate', 'type': 'iso-8601'},
        'to_effective_date': {'key': 'toEffectiveDate', 'type': 'iso-8601'},
        'from_as_at': {'key': 'fromAsAt', 'type': 'iso-8601'},
        'to_as_at': {'key': 'toAsAt', 'type': 'iso-8601'},
    }

    def __init__(self, action, from_effective_date=None, to_effective_date=None, from_as_at=None, to_as_at=None):
        super(RequestDetails, self).__init__()
        self.action = action
        self.from_effective_date = from_effective_date
        self.to_effective_date = to_effective_date
        self.from_as_at = from_as_at
        self.to_as_at = to_as_at
