# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RequestedActionKey(Model):
    """A fully qualified action identifier.

    :param entity_code: The type of the resource on which the activity would
     be performed
    :type entity_code: str
    :param scope: The scope/provider/vendor of the activity
    :type scope: str
    :param activity: The identifier of the action to be performed on the
     resource
    :type activity: str
    """

    _validation = {
        'entity_code': {'required': True, 'max_length': 100, 'min_length': 3},
        'scope': {'required': True, 'max_length': 100, 'min_length': 3},
        'activity': {'required': True, 'max_length': 100, 'min_length': 3},
    }

    _attribute_map = {
        'entity_code': {'key': 'entityCode', 'type': 'str'},
        'scope': {'key': 'scope', 'type': 'str'},
        'activity': {'key': 'activity', 'type': 'str'},
    }

    def __init__(self, entity_code, scope, activity):
        super(RequestedActionKey, self).__init__()
        self.entity_code = entity_code
        self.scope = scope
        self.activity = activity
