# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ResourceId(Model):
    """An identifier of a non-shrine resource.

    :param complex: Specify this type of resource identifier when addressing a
     resource with a ordered multi-part key
    :type complex: ~shrine.models.MultiPartResourceId
    :param scope_code: Specify this type of resource identifier when
     addressing a resource with a scope and a code
    :type scope_code: ~shrine.models.ScopeCodeResourceId
    :param full: Specify this type of resource identifier when addressing a
     resource with a scope, code and domain
    :type full: ~shrine.models.FullResourceId
    """

    _attribute_map = {
        'complex': {'key': 'complex', 'type': 'MultiPartResourceId'},
        'scope_code': {'key': 'scopeCode', 'type': 'ScopeCodeResourceId'},
        'full': {'key': 'full', 'type': 'FullResourceId'},
    }

    def __init__(self, complex=None, scope_code=None, full=None):
        super(ResourceId, self).__init__()
        self.complex = complex
        self.scope_code = scope_code
        self.full = full
