# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RoleIdentifier(Model):
    """RoleIdentifier.

    :param scope:
    :type scope: str
    :param code:
    :type code: str
    :param complex_keys:
    :type complex_keys: list[str]
    """

    _attribute_map = {
        'scope': {'key': 'scope', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'complex_keys': {'key': 'complexKeys', 'type': '[str]'},
    }

    def __init__(self, scope=None, code=None, complex_keys=None):
        super(RoleIdentifier, self).__init__()
        self.scope = scope
        self.code = code
        self.complex_keys = complex_keys
