# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ScopeAndCodeIdPathDefinition(Model):
    """ScopeAndCodeIdPathDefinition.

    :param scope:
    :type scope: str
    :param code:
    :type code: str
    """

    _attribute_map = {
        'scope': {'key': 'scope', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
    }

    def __init__(self, scope=None, code=None):
        super(ScopeAndCodeIdPathDefinition, self).__init__()
        self.scope = scope
        self.code = code
