# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CodeOnlyIdPathDefinition(Model):
    """CodeOnlyIdPathDefinition.

    :param code:
    :type code: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
    }

    def __init__(self, code=None):
        super(CodeOnlyIdPathDefinition, self).__init__()
        self.code = code
