# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IfIdentityScopeExpression(Model):
    """IfIdentityScopeExpression.

    :param scope_name:
    :type scope_name: str
    """

    _validation = {
        'scope_name': {'required': True, 'min_length': 1},
    }

    _attribute_map = {
        'scope_name': {'key': 'scopeName', 'type': 'str'},
    }

    def __init__(self, scope_name):
        super(IfIdentityScopeExpression, self).__init__()
        self.scope_name = scope_name
