# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Link(Model):
    """Link.

    :param relation:
    :type relation: str
    :param href:
    :type href: str
    :param description:
    :type description: str
    :param method: Possible values include: 'POST', 'GET', 'PATCH', 'DELETE',
     'PUT'
    :type method: str or ~shrine.models.enum
    """

    _validation = {
        'relation': {'required': True},
        'href': {'required': True},
        'method': {'required': True},
    }

    _attribute_map = {
        'relation': {'key': 'relation', 'type': 'str'},
        'href': {'key': 'href', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'method': {'key': 'method', 'type': 'str'},
    }

    def __init__(self, relation, href, method, description=None):
        super(Link, self).__init__()
        self.relation = relation
        self.href = href
        self.description = description
        self.method = method
