# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PolicyCollectionUpdateRequest(Model):
    """PolicyCollectionUpdateRequest.

    :param policy_ids:
    :type policy_ids: list[~shrine.models.PolicyId]
    :param attributes:
    :type attributes: dict[str, object]
    :param collection_ids:
    :type collection_ids: list[~shrine.models.PolicyCollectionId]
    """

    _attribute_map = {
        'policy_ids': {'key': 'policyIds', 'type': '[PolicyId]'},
        'attributes': {'key': 'attributes', 'type': '{object}'},
        'collection_ids': {'key': 'collectionIds', 'type': '[PolicyCollectionId]'},
    }

    def __init__(self, policy_ids=None, attributes=None, collection_ids=None):
        super(PolicyCollectionUpdateRequest, self).__init__()
        self.policy_ids = policy_ids
        self.attributes = attributes
        self.collection_ids = collection_ids
