# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PolicyCollectionResponse(Model):
    """PolicyCollectionResponse.

    :param id:
    :type id: ~shrine.models.PolicyCollectionId
    :param policy_ids:
    :type policy_ids: list[~shrine.models.PolicyId]
    :param attributes:
    :type attributes: dict[str, object]
    :param collection_ids:
    :type collection_ids: list[~shrine.models.PolicyCollectionId]
    :param _links:
    :type _links: list[~shrine.models.Link]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'PolicyCollectionId'},
        'policy_ids': {'key': 'policyIds', 'type': '[PolicyId]'},
        'attributes': {'key': 'attributes', 'type': '{object}'},
        'collection_ids': {'key': 'collectionIds', 'type': '[PolicyCollectionId]'},
        '_links': {'key': '_links', 'type': '[Link]'},
    }

    def __init__(self, id=None, policy_ids=None, attributes=None, collection_ids=None, _links=None):
        super(PolicyCollectionResponse, self).__init__()
        self.id = id
        self.policy_ids = policy_ids
        self.attributes = attributes
        self.collection_ids = collection_ids
        self._links = _links
