# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ResourceDetails(Model):
    """Details about the resource being requested that may be pertinent to the
    entitlement evaluation.

    :param id: The identifier of the resource being evaluated
    :type id: ~shrine.models.ResourceId
    :param attributes: Any attributes associated with the resource being
     requested
    :type attributes: dict[str, str]
    """

    _validation = {
        'id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'ResourceId'},
        'attributes': {'key': 'attributes', 'type': '{str}'},
    }

    def __init__(self, id, attributes=None):
        super(ResourceDetails, self).__init__()
        self.id = id
        self.attributes = attributes
