# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RoleCreationRequest(Model):
    """RoleCreationRequest.

    :param code:
    :type code: str
    :param description:
    :type description: str
    :param resource:
    :type resource: ~shrine.models.RoleResourceRequest
    :param when:
    :type when: ~shrine.models.WhenSpec
    """

    _validation = {
        'code': {'required': True, 'max_length': 50, 'min_length': 3},
        'resource': {'required': True},
        'when': {'required': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'resource': {'key': 'resource', 'type': 'RoleResourceRequest'},
        'when': {'key': 'when', 'type': 'WhenSpec'},
    }

    def __init__(self, code, resource, when, description=None):
        super(RoleCreationRequest, self).__init__()
        self.code = code
        self.description = description
        self.resource = resource
        self.when = when
