# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RoleResourceRequest(Model):
    """RoleResourceRequest.

    :param non_transitive_supervisor_role_resource:
    :type non_transitive_supervisor_role_resource:
     ~shrine.models.NonTransitiveSupervisorRoleResource
    :param policy_id_role_resource:
    :type policy_id_role_resource: ~shrine.models.PolicyIdRoleResource
    """

    _attribute_map = {
        'non_transitive_supervisor_role_resource': {'key': 'nonTransitiveSupervisorRoleResource', 'type': 'NonTransitiveSupervisorRoleResource'},
        'policy_id_role_resource': {'key': 'policyIdRoleResource', 'type': 'PolicyIdRoleResource'},
    }

    def __init__(self, non_transitive_supervisor_role_resource=None, policy_id_role_resource=None):
        super(RoleResourceRequest, self).__init__()
        self.non_transitive_supervisor_role_resource = non_transitive_supervisor_role_resource
        self.policy_id_role_resource = policy_id_role_resource
