# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ScopeCodeResourceId(Model):
    """A resource identifier comprised of a scope and a code.

    :param scope: The scope part of the resource identifier
    :type scope: str
    :param code: The code part of the resource identifier
    :type code: str
    """

    _validation = {
        'scope': {'required': True, 'max_length': 100, 'min_length': 3},
        'code': {'required': True, 'max_length': 100, 'min_length': 3},
    }

    _attribute_map = {
        'scope': {'key': 'scope', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
    }

    def __init__(self, scope, code):
        super(ScopeCodeResourceId, self).__init__()
        self.scope = scope
        self.code = code
