# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ScopeIdPathDefinition(Model):
    """ScopeIdPathDefinition.

    :param scope:
    :type scope: str
    """

    _attribute_map = {
        'scope': {'key': 'scope', 'type': 'str'},
    }

    def __init__(self, scope=None):
        super(ScopeIdPathDefinition, self).__init__()
        self.scope = scope
