# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .finbourne_shrine_api import FINBOURNEShrineAPI
from .version import VERSION

__all__ = ['FINBOURNEShrineAPI']

__version__ = VERSION

